import { StyleSheet } from "react-native";
import { BGColor, CardColor, FONT, MainColor } from "../../../../../constant/theme";

const styles = StyleSheet.create({
    // ... (Styles เดิมยังคงอยู่)
    backButton: {
        position: 'absolute',
        top: 40,
        left: 20,
        zIndex: 10,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#FFF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    container: {
        position: 'relative',
        flex: 1,
        backgroundColor: BGColor || '#F8F9FD',
    },
    center: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    errorText: {
        fontSize: 16,
        color: '#FF4D4F',
        fontFamily: FONT.REGULAR,
    },
    headerContainer: {
        backgroundColor: CardColor || '#FFF',
        alignItems: 'center',
        paddingTop: 40,
        paddingBottom: 30,
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
        borderWidth: 1,
        borderColor: '#e5e3e3',
        marginBottom: 24,
    },
    profileWrapper: {
        position: 'relative',
        marginBottom: 12, // ลดลงเล็กน้อย
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 8,
    },
    profileImage: {
        width: 110,
        height: 110,
        borderRadius: 55,
        backgroundColor: '#F0F0F0',
        borderWidth: 4,
        borderColor: '#FFF',
    },
    onlineStatus: {
        position: 'absolute',
        bottom: 5,
        right: 5,
        width: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: '#4CAF50',
        borderWidth: 2,
        borderColor: '#FFF',
    },
    providerName: {
        fontSize: 24,
        fontFamily: FONT.BOLD,
        color: '#1A1A1A',
        marginBottom: 4,
        textAlign: 'center',
    },
    // เพิ่ม Style สำหรับ Rating ที่ Header
    headerRatingBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF8E1', // สีเหลืองอ่อน
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        marginBottom: 12,
    },
    headerRatingText: {
        fontSize: 12,
        fontFamily: FONT.BOLD,
        color: '#F57F17', // สีส้มเข้ม/ทอง
        marginLeft: 4,
    },
    tagContainer: {
        flexDirection: 'row',
        marginBottom: 20,
    },
    tagBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: `${MainColor}15`,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    tagText: {
        fontSize: 12,
        fontFamily: FONT.BOLD,
        color: MainColor,
        marginLeft: 4,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
    },
    infoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    infoText: {
        fontSize: 14,
        fontFamily: FONT.REGULAR,
        color: '#555',
        marginLeft: 8,
    },
    dividerVertical: {
        width: 1,
        height: 20,
        backgroundColor: '#E0E0E0',
    },
    sectionContainer: {
        paddingHorizontal: 24,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: FONT.BOLD,
        color: '#1A1A1A',
    },
    serviceCount: {
        fontSize: 12,
        fontFamily: FONT.REGULAR,
        color: '#888',
        marginBottom: 2,
    },
    serviceCard: {
        backgroundColor: CardColor || '#FFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 14,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e5e3e3',
    },
    serviceIconBox: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: `${MainColor}10`,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    serviceInfo: {
        flex: 1,
    },
    serviceName: {
        fontSize: 16,
        fontFamily: FONT.BOLD,
        color: '#333',
        marginBottom: 4,
    },
    bookButton: {
        backgroundColor: MainColor,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
        shadowColor: MainColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    bookButtonText: {
        color: '#FFF',
        fontSize: 14,
        fontFamily: FONT.BOLD,
    },
    emptyContainer: {
        alignItems: 'center',
        marginTop: 40,
        opacity: 0.7,
    },
    emptyText: {
        marginTop: 10,
        fontFamily: FONT.REGULAR,
        color: '#999',
    },

    // --- Review Section Styles (NEW) ---
    reviewSummaryCard: {
        backgroundColor: '#FFF',
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#EFEFEF',
        // Shadow เบาๆ
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    ratingBigContainer: {
        alignItems: 'center',
        paddingRight: 20,
        borderRightWidth: 1,
        borderRightColor: '#EEE',
        marginRight: 20,
    },
    ratingBigNumber: {
        fontSize: 36,
        fontFamily: FONT.BOLD,
        color: '#333',
        lineHeight: 42,
    },
    ratingTotalText: {
        fontSize: 10,
        color: '#888',
        marginTop: 4,
        fontFamily: FONT.REGULAR,
    },
    ratingBarContainer: {
        flex: 1,
        justifyContent: 'center',
    },
    ratingBarText: {
        fontSize: 12,
        fontFamily: FONT.BOLD,
        color: '#555',
        marginBottom: 8,
    },
    ratingProgressBg: {
        height: 8,
        backgroundColor: '#F0F0F0',
        borderRadius: 4,
        overflow: 'hidden',
    },
    ratingProgressFill: {
        height: '100%',
        backgroundColor: MainColor, // หรือสีเหลืองทอง #FFD700
        borderRadius: 4,
    },
    // Review Card
    reviewCard: {
        backgroundColor: '#FFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#F5F5F5',
    },
    reviewHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    reviewerInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    reviewerAvatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#DDD', // สีเทา Placeholder
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    reviewerName: {
        fontSize: 14,
        fontFamily: FONT.BOLD,
        color: '#333',
    },
    reviewStarsRow: {
        flexDirection: 'row',
        marginTop: 2,
    },
    reviewDate: {
        fontSize: 10,
        color: '#999',
        fontFamily: FONT.REGULAR,
    },
    reviewContent: {
        backgroundColor: '#F9F9F9', // พื้นหลังข้อความให้ดูแยกออกมา
        padding: 12,
        borderRadius: 8,
    },
    reviewText: {
        fontSize: 13,
        color: '#555',
        fontFamily: FONT.REGULAR,
        lineHeight: 20,
        fontStyle: 'italic', // ทำให้ดูเหมือนคำพูด
    },
    emptyReviewContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 30,
        backgroundColor: '#F9F9F9',
        borderRadius: 12,
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: '#DDD',
    },

    // --- Modal Styles (เหมือนเดิม) ---
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)', 
        justifyContent: 'center', 
        padding: 20,
    },
    modalContent: {
        backgroundColor: '#FFF',
        borderRadius: 24,
        padding: 24,
        maxHeight: '80%',
        width: '100%',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.25,
        shadowRadius: 20,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        paddingBottom: 15,
    },
    modalTitle: {
        fontSize: 20,
        fontFamily: FONT.BOLD,
        color: '#333',
    },
    closeButton: {
        padding: 4,
        backgroundColor: '#F5F5F5',
        borderRadius: 20,
    },
    label: {
        fontSize: 14,
        fontFamily: FONT.BOLD,
        color: '#444',
        marginBottom: 8,
        marginTop: 10,
    },
    readOnlyField: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#EFEFEF',
        marginBottom: 10,
    },
    readOnlyText: {
        color: '#333',
        fontSize: 16,
        fontFamily: FONT.BOLD,
    },
    textArea: {
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 12,
        padding: 16,
        height: 120,
        textAlignVertical: 'top',
        fontSize: 16,
        fontFamily: FONT.REGULAR,
        color: '#333',
    },
    hintText: {
        fontSize: 12,
        color: '#999',
        fontFamily: FONT.REGULAR,
        marginTop: 6,
        fontStyle: 'italic',
        marginBottom: 20,
    },
    modalFooter: {
        flexDirection: 'row',
        marginTop: 10,
        gap: 12, 
    },
    modalButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButton: {
        backgroundColor: '#F5F5F5',
    },
    confirmButton: {
        backgroundColor: MainColor,
        shadowColor: MainColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    cancelButtonText: {
        color: '#666',
        fontSize: 16,
        fontFamily: FONT.BOLD,
    },
    confirmButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontFamily: FONT.BOLD,
    }
});


export default styles